#!/usr/bin/env bash
#
# Walks a maintainer through creating the secrets the release workflow signs and notarizes Suru's macOS binary
# with (ADR-0050), and sets them on the repository: the Developer ID Application certificate as a p12 and its
# password, the Team ID, and an App Store Connect API key with its Key ID and Issuer ID. Re-run it to renew the
# certificate or rotate the key; it offers to keep any secret already set.
#
#   scripts/macos-signing-wizard.sh
#
# Needs a Mac, a team in the Apple Developer Program whose Account Holder can create a Developer ID certificate,
# and gh logged in as someone who can set the repository's secrets.
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# Every secret named here must match one .github/workflows/build.yml reads.
P12_SECRETS=(APPLE_DEVELOPER_ID_P12_BASE64 APPLE_DEVELOPER_ID_P12_PASSWORD)
API_KEY_SECRETS=(APPLE_API_KEY APPLE_API_KEY_ID APPLE_API_ISSUER_ID)

die() { printf '%s✗ %s%s\n' "$RED" "$1" "$RESET" >&2; exit 1; }

[[ "$(uname -s)" == Darwin ]] || die "This wizard needs a Mac: the certificate is exported from Keychain Access."
command -v gh >/dev/null 2>&1 || die "This wizard needs the GitHub CLI (gh) to set the secrets: https://cli.github.com"
gh auth status >/dev/null 2>&1 || die "Log in to GitHub first: gh auth login"
# gh finds the repository from the checkout this script lives in.
cd "$(dirname "${BASH_SOURCE[0]}")/.."
REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner) || die "gh can't tell which repository this is."
export GH_REPO="$REPO"

# keep_existing NAME... asks whether to keep secrets the repository already has. Succeeds when every one is set
# and the human keeps them, so a re-run can skip what an earlier run finished.
keep_existing() {
  local existing name
  existing=$(gh secret list --json name --jq '.[].name')
  for name in "$@"; do
    grep -qx "$name" <<< "$existing" || return 1
  done
  note "$REPO already has $*."
  if confirm "Replace them?"; then return 1; fi
  printf '  %s✓ kept%s %s\n' "$GREEN" "$RESET" "$*"
  pause "Press Enter to continue"
}

# ask_path KEY "Prompt" [DEFAULT] reads the path of an existing file into $KEY. Takes a path dragged in from
# Finder, which escapes its spaces and leaves a trailing one.
ask_path() {
  local key="$1" prompt="$2" default="${3:-}" input
  while :; do
    if [[ -n "$default" ]]; then
      printf '  %s%s%s %s[Enter for %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$default" "$RESET"
    else
      printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    read -r input || true
    input="${input%"${input##*[![:space:]]}"}"
    input="${input//\\ / }"
    [[ -z "$input" ]] && input="$default"
    input="${input/#\~/$HOME}"
    if [[ -f "$input" ]]; then
      printf -v "$key" '%s' "$input"
      return
    fi
    warn "No file at ${input:-that path}; try again."
  done
}

# developer_id_identities lists the Developer ID Application identities in the login keychain.
developer_id_identities() {
  security find-identity -v -p codesigning 2>/dev/null |
    sed -n 's/.*"\(Developer ID Application: [^"]*\)".*/\1/p' | sort -u
}

# p12_identity PATH PASSWORD prints the Developer ID Application identity a p12 holds, by importing it into a
# throwaway keychain as the release workflow does. Fails when the password is wrong or the p12 holds no such
# identity.
p12_identity() (
  local dir keychain identity=""
  dir=$(mktemp -d)
  keychain="$dir/check.keychain-db"
  trap 'security delete-keychain "$keychain" >/dev/null 2>&1; rm -rf "$dir"' EXIT
  security create-keychain -p check "$keychain" >/dev/null 2>&1
  security import "$1" -k "$keychain" -f pkcs12 -P "$2" >/dev/null 2>&1 || return 1
  identity=$(security find-identity -p codesigning "$keychain" |
    sed -n 's/.*"\(Developer ID Application: [^"]*\)".*/\1/p' | head -n1)
  [[ -n "$identity" ]] && printf '%s\n' "$identity"
)

banner "Suru macOS release signing for $REPO"

TEAM_ID=""

stage "Developer ID Application certificate"
# Keeping the certificate already set skips its export as well.
if ! keep_existing "${P12_SECRETS[@]}"; then
  say "Releases are signed with your team's Developer ID Application certificate."
  identities=$(developer_id_identities)
  if [[ -z "$identities" ]]; then
    say "None is in your login keychain yet, so create one. Only your team's Account Holder can."
    open_url "https://developer.apple.com/account/resources/certificates/add"
    step "Choose 'Developer ID Application', then Continue, and the G2 Sub-CA."
    step "It asks for a Certificate Signing Request. Make one in Keychain Access:"
    note "    Keychain Access → Certificate Assistant → Request a Certificate From a Certificate Authority…,"
    note "    your email, 'Saved to disk'."
    step "Upload the .certSigningRequest, Continue, then Download the certificate."
    step "Double-click the downloaded .cer; it joins your login keychain beside its private key."
    pause "Press Enter once it's in your keychain"
    identities=$(developer_id_identities)
  fi
  if [[ -n "$identities" ]]; then
    say "Your login keychain has:"
    while IFS= read -r identity; do step "$identity"; done <<< "$identities"
  else
    warn "Your login keychain lists no valid one yet. If Keychain Access shows it as untrusted, install"
    warn "Apple's 'Developer ID - G2' intermediate from https://www.apple.com/certificateauthority/."
  fi
  pause "Press Enter to export it"

  stage "Export the certificate as a .p12"
  open -a "Keychain Access" || warn "couldn't open Keychain Access; open it from Spotlight"
  step "In the login keychain's My Certificates, select 'Developer ID Application: … (your Team ID)'."
  step "Expand it: its private key must be beneath it, or the export can't sign anything."
  step "File → Export Items…, format Personal Information Exchange (.p12)."
  step "Save it to your Desktop as suru-developer-id.p12, and give it a strong password."
  ask_path P12_PATH "Path to the .p12:" "$HOME/Desktop/suru-developer-id.p12"
  while :; do
    ask_secret P12_PASSWORD "The password you exported it with:"
    if [[ -z "$P12_PASSWORD" ]]; then
      warn "The release needs a password on the p12; export it again with one."
      continue
    fi
    if identity=$(p12_identity "$P12_PATH" "$P12_PASSWORD"); then break; fi
    warn "That password doesn't open it, or it holds no Developer ID Application identity with its key."
  done
  printf '  %s✓ holds%s %s\n' "$GREEN" "$RESET" "$identity"
  TEAM_ID=${identity##*(}
  TEAM_ID=${TEAM_ID%)}
  set_secret APPLE_DEVELOPER_ID_P12_BASE64 "$(base64 < "$P12_PATH" | tr -d '\n')"
  set_secret APPLE_DEVELOPER_ID_P12_PASSWORD "$P12_PASSWORD"
  if confirm "Delete $P12_PATH now? The certificate stays in your login keychain."; then
    rm -f "$P12_PATH"
    printf '  %s✓ deleted%s %s\n' "$GREEN" "$RESET" "$P12_PATH"
  fi
  pause "Press Enter to continue"
fi

stage "Team ID"
warn "Every Suru release must come from one team, signed as ai.suru.cli: the keychain trusts that pair."
warn "Another team brings 'suru wants to use your confidential information' back for every user."
note "A renewed certificate from the same team is fine."
if [[ -n "$TEAM_ID" ]]; then
  say "The certificate you exported belongs to team $TEAM_ID."
  set_secret APPLE_TEAM_ID "$TEAM_ID"
  pause "Press Enter to continue"
elif ! keep_existing APPLE_TEAM_ID; then
  open_url "https://developer.apple.com/account"
  step "Under Membership details, copy the Team ID: ten letters and digits."
  while :; do
    ask TEAM_ID "Team ID:"
    [[ "$TEAM_ID" =~ ^[A-Z0-9]{10}$ ]] && break
    warn "A Team ID is ten capital letters and digits, like A1B2C3D4E5."
  done
  set_secret APPLE_TEAM_ID "$TEAM_ID"
  pause "Press Enter to continue"
fi

stage "App Store Connect API key, for notarization"
if ! keep_existing "${API_KEY_SECRETS[@]}"; then
  open_url "https://appstoreconnect.apple.com/access/integrations/api"
  step "Under Team Keys, click + (the first time, the Account Holder must Request Access)."
  step "Name it 'Suru notarization', give it Developer access, then Generate."
  step "Download API Key on its row. Apple offers the download only once."
  step "Copy the Issuer ID shown above the list of keys."
  latest_key=""
  for downloaded in "$HOME"/Downloads/AuthKey_*.p8; do
    if [[ -f "$downloaded" && ( -z "$latest_key" || "$downloaded" -nt "$latest_key" ) ]]; then
      latest_key=$downloaded
    fi
  done
  while :; do
    ask_path P8_PATH "Path to the AuthKey_….p8:" "$latest_key"
    API_KEY_ID=""
    if [[ "$(basename "$P8_PATH")" =~ ^AuthKey_([A-Z0-9]+)\.p8$ ]]; then
      API_KEY_ID=${BASH_REMATCH[1]}
      say "Its Key ID is $API_KEY_ID."
    else
      ask API_KEY_ID "Key ID (on the key's row):"
    fi
    while :; do
      ask API_ISSUER_ID "Issuer ID:"
      [[ "$API_ISSUER_ID" =~ ^[0-9a-fA-F-]{36}$ ]] && break
      warn "An Issuer ID is a UUID, like 69a6de70-03db-47e3-e053-5b8c7c11a4d1."
    done
    if ! xcrun --find notarytool >/dev/null 2>&1; then
      warn "notarytool isn't installed (xcode-select --install), so the key is uploaded untried."
      break
    fi
    say "Asking Apple's notary service whether it takes the key…"
    if output=$(xcrun notarytool history --key "$P8_PATH" --key-id "$API_KEY_ID" --issuer "$API_ISSUER_ID" 2>&1); then
      printf '  %s✓ accepted%s by the notary service\n' "$GREEN" "$RESET"
      break
    fi
    printf '%s\n' "$output" | sed 's/^/    /'
    confirm "The notary service turned it down. Enter the key again? (No uploads it as it is.)" || break
  done
  set_secret APPLE_API_KEY "$(cat "$P8_PATH")"
  set_secret APPLE_API_KEY_ID "$API_KEY_ID"
  set_secret APPLE_API_ISSUER_ID "$API_ISSUER_ID"
  note "Keep $(basename "$P8_PATH") in a password manager, or delete it and generate another key when you need one."
  if confirm "Delete $P8_PATH now?"; then
    rm -f "$P8_PATH"
    printf '  %s✓ deleted%s %s\n' "$GREEN" "$RESET" "$P8_PATH"
  fi
  pause "Press Enter to finish"
fi

finish
say "The next release signs and notarizes its macOS binary. To check a released binary:"
note "  codesign --verify --strict suru && codesign -d -r- suru"
note "Its designated requirement names identifier \"ai.suru.cli\" and your Team ID."
printf '\n'
